apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
specs:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      label:
        component: web
    spec:
      - name: client
        image: calvincolton/fibonacci-client
        ports:
          - containerPort: 3000
